name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy rustfmt
      - name: Clippy
        run: cargo clippy --no-default-features -- -D warnings
      - name: Clippy (all)
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --no-default-features --verbose
      - name: Run tests with all features
        run: cargo test --all-features --verbose
